function conratio2
global I
clc
h_figure=figure('Units','characters',...
    'Position',[80 3 120 35],...
    'Color',get(0,'DefaultUicontrolBackgroundColor'),'toolbar','figure');
h_axes=axes('Units','characters',...
    'Position',[10 0 70 25],...
    'Parent',h_figure);
I = imread('chin11.jpg');
axes(h_axes)
imshow(I)
h1= uicontrol('parent',h_figure,...
    'Style','slider',...
    'Units','characters',...
    'tag','h1',...
    'Position',[88 5 24 2],...
    'TooltipString','lOW_IN');
h2 = uicontrol(h_figure,...
    'Style','slider',...
    'Units','characters',...
    'Position',[88 8 24 2],...
    'TooltipString','HIGH_IN','value',0.2);
h3 = uicontrol(h_figure,...
    'Style','slider',...
    'Units','characters',...
    'Position',[88 11 24 2],...
    'TooltipString','lOW_OUT');
h4 = uicontrol(h_figure,...
    'Style','slider',...
    'Units','characters',...
    'Position',[88 14 24 2],...
    'TooltipString','HIGH_OUT','value',0.2);
h5 = uicontrol(h_figure,...
    'Style','pushbutton',...
    'Units','characters',...
    'Position',[88 20 24 2],...
    'String','Help','callback',{@help_callback,h_figure});
set(h1,'callback',{@adjust_callback,h1,h2,h3,h4,h_axes})
set(h2,'callback',{@adjust_callback,h1,h2,h3,h4,h_axes})
set(h3,'callback',{@adjust_callback,h1,h2,h3,h4,h_axes})
set(h4,'callback',{@adjust_callback,h1,h2,h3,h4,h_axes})

function adjust_callback(obj,eventdata,h1,h2,h3,h4,h_axes)
I = imread('chin11.jpg');
a = rand(1,2);
b = rand(1,2);
a(1) = get(h1,'value');
a(2) = get(h2,'value');
b(1) = get(h3,'value');
b(2) = get(h4,'value');
I=imadjust(I,a,b);
axes(h_axes)
imshow(I)
function help_callback(obj,eventdata,h_figure)
uicontrol(h_figure,'style','text','horizontalalignment','left','pos',[10 350 800 60],'string','The first slider should be less than the second one,the third slider should be less than the fourth one')
